### ISSUE TITLE
[BUG] saved articles fail to load

### ISSUE THREAD

**Issue by hjek** [nsh07/WikiReader#201]
### Describe the bug
Saved articles fail to load

### To Reproduce
1. Open an article
2. Save article
3. Restart WR
4. Open saved article

### Expected behavior
Saved article would be loaded.

**Comment by hjek** [comment]
![Image](https://github.com/user-attachments/assets/c7fde0ae-552c-49c9-982a-5dd613969fff)

**Comment by nsh07** [comment]
This will be fixed in 2.4, which I am planning to release next week. Sorry for the delay, I just want to release the new article saving system with other improvements

**Comment by nsh07** [comment]
This bug is fixed in [2.4.0](https://github.com/nsh07/WikiReader/releases/tag/v2.4.0)

**Comment by ildar** [comment]
related: https://github.com/nsh07/WikiReader/issues/33

The app still doesn't show Saved pages while **offline** i.e. disconnected from the internet.

**Comment by nsh07** [comment]
@ildar offline articles appear to be working fine for me on version 2.5.1. Can you please attach a screen recording of the bug with steps on how to reproduce it?
