### ISSUE TITLE
[Bug] Missing a lot of information from articles

### ISSUE THREAD

**Issue by Disonantemus** [nsh07/WikiReader#25]
## Bug

**WikiReader** is _missing a lot of information_ from the articles, like: tables, references, external links and links from the articles to other articles.

---

Example: [Article: "Rebecca Ferguson"](https://en.wikipedia.org/wiki/Rebecca_Ferguson)

**Wikireader** (screenshot): Using [Last release v1.70](https://github.com/nsh07/WikiReader/releases/tag/v1.7.0)

![Screenshot_20241115_161941_WikiReader.png](https://github.com/user-attachments/assets/eb525286-8a4f-447c-ae96-136122cf9eed)

As you can see, is missing information in 4 main sections:

- _Filmography:_ **empty subsections**
  - Film
  - Television
  - Podcast
- _Awards and nominations:_ **none**
- _References:_ **none**
- _External links:_ **shows 3 from 94** titles (with no links)

## Summary

From other topics that I've tried, **WikiReader** doesn't work with:
- any kind of tables with information
- references
- external links
- doesn't show/work with links to other articles inside wikipedia.

---

_WikiReader_ works similar to [wikicurses (no commit in 6 years)](https://github.com/ids1024/wikicurses), is a [cliwiki (no commit in 12 years)](https://github.com/AnirudhBhat/cliWiki.py) fork, both made in python, but this does work with references and external links.

**Comment by nsh07** [comment]
This issue reports a known bug that I knew would be reported some day or the other, that I've been avoiding since quite a while (😆)

The current issue with my approach to getting the Wikipedia text is that it *strips any content that isn't pure text* out of the article. So reference superscripts, mathematical expressions (#24), tables, links, references etc are lost.

I cannot add support for external links because this app is meant to be distraction-free and intended for pure reading, so it should not open links that lead to other apps (your web browser). Also loading tables can be quite complex. So I'm thinking of doing two things:

- Remove References and External Links from the page because they fundamentally cannot be implemented. This can be implemented quickly and I can implement it in the next release
- Add support for mathematical expressions and tables somehow (this can take quite some time, but I'm willing to do it)

Also see #11 which I am planning to implement in the next release

I would like to hear your opinion on this

**Comment by Disonantemus** [comment]
1. Internal links to other wikipedia articles.
2. Tables.

Both are used almost at every page and are really essential, because information and to not search again for something that already has a link. Math not so much and can wait. 

---

I understand your reasoning references and external links.

**Comment by nsh07** [comment]
I'm currently working on adding internal links and will work on adding tables soon. Thanks for the suggestions! :)

**Comment by nsh07** [comment]
Hey, I've added support for internal links in the "See Also" section and in disambiguation pages. The design is quite different than usual, so I'd love to hear your feedback at #11

**Comment by nsh07** [comment]
Most of the issues proposed in this issue are now resolved. The only remaining missing content is the Infobox, which is mentioned in #77 

I am closing this issue as completed now, you can reopen it if there is any other missing content. You can also continue the discussion about Infoboxes at #77

**Comment by Disonantemus** [comment]
I did test this now, with last version from F-Droid (1.10.3) and is still not fixed, maybe all the changes are done in the 2.0 dev fork?

**Comment by nsh07** [comment]
> I did test this now, with last version from F-Droid (1.10.3) and is still not fixed, maybe all the changes are done in the 2.0 dev fork?

Yes, you need to download the APK manually from the Releases on GitHub. I have not released the development updates on F-Droid

**Comment by Disonantemus** [comment]
> > I did test this now, with last version from F-Droid (1.10.3) and is still not fixed, maybe all the changes are done in the 2.0 dev fork?
> 
> Yes, you need to download the APK manually from the Releases on GitHub. I have not released the development updates on F-Droid

I wasn't aware, because from [here](https://github.com/nsh07/WikiReader), you can see only (same as my phone):

    Releases 30
    v1.10.3 [ Latest ]
    2 weeks ago

But when you click in Releases, last one is:

    v2.0.0-06-alpha [ Pre-release ]

**Comment by nsh07** [comment]
Yeah, it's a GitHub thing lol, they don't show pre-release versions as "latest" releases
